name: Pull Request Validator
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

  workflow_dispatch:

jobs:
  shared:
    uses: avnes/action-workflows/.github/workflows/ansible-pr-validator.yaml@main
